# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./src"
  bin = "tmp/main"
  full_bin = "tmp/main"

  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]

[log]
  time = true

[app]
  kill_delay = 1000  # milliseconds
